// Mock dataset for Demo / Standalone mode when backend is not connected

export const mockCandidates = [
  {
    id: 1,
    job_title: "Senior Full Stack Developer",
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    phone: "+91 98765 43210",
    resume: "resumes/aarav_sharma_cv.pdf",
    applied_at: "2026-09-28T10:30:00.000Z",
  },
  {
    id: 2,
    job_title: "HR Operations Lead",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    phone: "+91 98123 45678",
    resume: "resumes/priya_patel_cv.pdf",
    applied_at: "2026-09-29T11:15:00.000Z",
  },
  {
    id: 3,
    job_title: "UI/UX Product Designer",
    name: "Rohan Verma",
    email: "rohan.verma@example.com",
    phone: "+91 97234 56789",
    resume: "resumes/rohan_verma_cv.pdf",
    applied_at: "2026-09-30T14:45:00.000Z",
  },
  {
    id: 4,
    job_title: "DevOps Engineer",
    name: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    phone: "+91 96345 67890",
    resume: "resumes/sneha_reddy_cv.pdf",
    applied_at: "2026-10-01T09:20:00.000Z",
  },
  {
    id: 5,
    job_title: "Talent Acquisition Specialist",
    name: "Ananya Gupta",
    email: "ananya.gupta@example.com",
    phone: "+91 95456 78901",
    resume: "resumes/ananya_gupta_cv.pdf",
    applied_at: "2026-10-01T16:10:00.000Z",
  },
  {
    id: 6,
    job_title: "React Frontend Developer",
    name: "Vikram Malhotra",
    email: "vikram.m@example.com",
    phone: "+91 94567 89012",
    resume: "resumes/vikram_m_cv.pdf",
    applied_at: "2026-10-02T13:00:00.000Z",
  },
];

export const mockJobs = [
  {
    id: 1,
    title: "Senior Full Stack Developer",
    department: "Engineering",
    location: "Remote / Hybrid",
    type: "Full-Time",
    experience: "4-6 Years",
    openings: 2,
    status: "Active",
    created_at: "2026-09-15",
  },
  {
    id: 2,
    title: "HR Operations Lead",
    department: "Human Resources",
    location: "Onsite",
    type: "Full-Time",
    experience: "3-5 Years",
    openings: 1,
    status: "Active",
    created_at: "2026-09-18",
  },
  {
    id: 3,
    title: "UI/UX Product Designer",
    department: "Product Design",
    location: "Remote",
    type: "Full-Time",
    experience: "2-4 Years",
    openings: 1,
    status: "Active",
    created_at: "2026-09-20",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    department: "Infrastructure",
    location: "Hybrid",
    type: "Full-Time",
    experience: "3-6 Years",
    openings: 1,
    status: "Active",
    created_at: "2026-09-22",
  },
];

export const mockEmployees = [
  {
    id: "EMP-101",
    name: "Rahul Mehra",
    role: "Engineering Director",
    department: "Engineering",
    email: "rahul.m@company.com",
    phone: "+91 98765 11223",
    location: "Mumbai HQ (Hybrid)",
    status: "Active",
    joinedDate: "2023-04-12",
    employmentType: "Full-Time, Permanent",
    manager: "Chief Technology Officer",
    salary: "$140,000 / year",
    payCycle: "Monthly Direct Deposit",
    emergencyContact: "Anjali Mehra (Spouse) • +91 98765 99887",
    attendanceRate: "98.4%",
    leavesRemaining: "15 / 18 Days",
    skills: ["System Design", "Node.js", "React", "AWS Cloud", "Team Leadership"],
  },
  {
    id: "EMP-102",
    name: "Neha Singhania",
    role: "Lead Product Designer",
    department: "Product Design",
    email: "neha.s@company.com",
    phone: "+91 98123 44556",
    location: "Bengaluru (Remote)",
    status: "Active",
    joinedDate: "2023-08-19",
    employmentType: "Full-Time, Permanent",
    manager: "VP of Product",
    salary: "$115,000 / year",
    payCycle: "Monthly Direct Deposit",
    emergencyContact: "Ramesh Singhania (Father) • +91 98123 00112",
    attendanceRate: "97.1%",
    leavesRemaining: "12 / 18 Days",
    skills: ["Figma", "Design Systems", "User Research", "Prototyping", "UX Strategy"],
  },
  {
    id: "EMP-103",
    name: "Karan Johar",
    role: "Senior HR Specialist",
    department: "Human Resources",
    email: "karan.j@company.com",
    phone: "+91 97234 66778",
    location: "Delhi NCR (Onsite)",
    status: "Active",
    joinedDate: "2024-01-10",
    employmentType: "Full-Time, Permanent",
    manager: "Head of People & Culture",
    salary: "$85,000 / year",
    payCycle: "Monthly Direct Deposit",
    emergencyContact: "Sunita Johar (Mother) • +91 97234 88990",
    attendanceRate: "99.0%",
    leavesRemaining: "16 / 18 Days",
    skills: ["Talent Sourcing", "Payroll Compliance", "Conflict Resolution", "Onboarding"],
  },
  {
    id: "EMP-104",
    name: "Tanvi Saxena",
    role: "Frontend Engineer",
    department: "Engineering",
    email: "tanvi.s@company.com",
    phone: "+91 96345 77889",
    location: "Mumbai HQ (Hybrid)",
    status: "Active",
    joinedDate: "2024-05-15",
    employmentType: "Full-Time, Permanent",
    manager: "Rahul Mehra",
    salary: "$95,000 / year",
    payCycle: "Monthly Direct Deposit",
    emergencyContact: "Vikas Saxena (Brother) • +91 96345 11234",
    attendanceRate: "96.5%",
    leavesRemaining: "14 / 18 Days",
    skills: ["Next.js 15", "React 19", "Tailwind CSS", "TypeScript", "Redux Toolkit"],
  },
  {
    id: "EMP-105",
    name: "Aditya Roy",
    role: "Marketing Strategist",
    department: "Marketing",
    email: "aditya.r@company.com",
    phone: "+91 95456 88990",
    location: "Pune (Remote)",
    status: "On Leave",
    joinedDate: "2024-09-01",
    employmentType: "Full-Time, Permanent",
    manager: "Chief Marketing Officer",
    salary: "$82,000 / year",
    payCycle: "Monthly Direct Deposit",
    emergencyContact: "Pooja Roy (Spouse) • +91 95456 33445",
    attendanceRate: "94.0%",
    leavesRemaining: "8 / 18 Days",
    skills: ["Growth Marketing", "Content Strategy", "SEO", "HubSpot", "Data Analytics"],
  },
];

export const mockInterviews = [
  {
    id: 1,
    candidate: "Aarav Sharma",
    role: "Senior Full Stack Developer",
    interviewer: "Rahul Mehra (Tech Lead)",
    type: "System Architecture Round",
    date: "Tomorrow, 10:30 AM",
    status: "Scheduled",
  },
  {
    id: 2,
    candidate: "Priya Patel",
    role: "HR Operations Lead",
    interviewer: "Karan Johar (HR)",
    type: "Culture Fit & Salary Discussion",
    date: "Tomorrow, 02:00 PM",
    status: "Scheduled",
  },
  {
    id: 3,
    candidate: "Rohan Verma",
    role: "UI/UX Product Designer",
    interviewer: "Neha Singhania (Design Lead)",
    type: "Figma Case Study Review",
    date: "Oct 05, 11:00 AM",
    status: "Confirmed",
  },
  {
    id: 4,
    candidate: "Sneha Reddy",
    role: "DevOps Engineer",
    interviewer: "DevOps Team Lead",
    type: "Kubernetes & AWS Technical",
    date: "Oct 06, 04:00 PM",
    status: "Pending Confirmation",
  },
];
